name: "Publish Package"

env:
  WT_GITHUB_TOKEN: ${{secrets.WT_GITHUB_PACKAGES_RO}}
  GITHUB_TOKEN: ${{secrets.WT_GITHUB_PACKAGES_RO}}
  NPM_PUBLISH_ACCESS_TOKEN: ${{ secrets.WT_GITHUB_REPO_RO_PACKAGES_RW }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup

      - name: Run linting
        run: yarn lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test

  version:
    name: Bump Version and Tag
    runs-on: ubuntu-latest
    needs: [linting, unit-test]
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Bump version
        id: version
        run: |
          # Bump version using yarn version
          yarn version --patch

          # Extract the new version
          echo "NEW_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [linting, unit-test]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags

      - name: Build package
        run: yarn build

      - name: Publish package
        run: yarn publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: "$NPM_PUBLISH_ACCESS_TOKEN"
