name: "Publish Package"

env:
  WT_GITHUB_TOKEN: ${{secrets.WT_GITHUB_PACKAGES_RO}}
  GITHUB_TOKEN: ${{secrets.WT_GITHUB_PACKAGES_RO}}
  NPM_PUBLISH_ACCESS_TOKEN: ${{ secrets.WT_GITHUB_REPO_RO_PACKAGES_RW }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "**" # Allow the workflow to be triggered on any branch for testing

permissions:
  packages: write
  contents: write

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup
        with:
          env: ${{ env.GITHUB_TOKEN }}

      - name: Run linting
        run: yarn lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test

  version:
    name: Bump Version and Tag
    runs-on: ubuntu-latest
    needs: [linting, unit-test]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }} # Use the current branch name

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup git permissions
        run: |
          git config --global user.name "wetransferplatform"
          git config --global user.email "platform+github@wetransfer.com"
          git config --global user.signingkey "$WETRANSFERPLATFORM_SIGNIN_KEY"
          git config --global commit.gpgsign true
        shell: bash
        env:
          WETRANSFERPLATFORM_SIGNIN_KEY: ${{ secrets.WETRANSFERPLATFORM_GPG_KEYID }}

      - name: Bump version
        id: version
        run: |
          # Bump version using yarn version
          yarn version --patch

          # Extract the new version
          echo "NEW_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: Push changes and tags
        run: |
          git add --all
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git tag -a "v${{ env.NEW_VERSION }}" -m "Release version ${{ env.NEW_VERSION }}"
          git push origin feat/public-migration --follow-tags

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }} # Use the current branch name

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn build

      - name: Publish package
        run: yarn publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACCESS_TOKEN }}
