name: "Publish Package"

env:
  WT_GITHUB_TOKEN: ${{secrets.WT_GITHUB_PACKAGES_RO}}
  GITHUB_TOKEN: ${{secrets.WT_GITHUB_PACKAGES_RO}}
  NPM_PUBLISH_ACCESS_TOKEN: ${{ secrets.WT_GITHUB_REPO_RO_PACKAGES_RW }}
  WETRANSFERPLATFORM_GPG_KEYID: ${{ secrets.WETRANSFERPLATFORM_GPG_KEYID }}
  WETRANSFERPLATFORM_GPG_KEY: ${{ secrets.WETRANSFERPLATFORM_GPG_KEY }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "**" # Allow the workflow to be triggered on any branch for testing

permissions:
  id-token: write
  packages: write
  contents: write

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup
        with:
          env: ${{ env.GITHUB_TOKEN }}

      - name: Run linting
        run: yarn lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          env: ${{ env.GITHUB_TOKEN }}

      - name: Run unit tests
        run: yarn test

  version:
    name: Bump Version and Tag
    runs-on: ubuntu-latest
    needs: [linting, unit-test]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }} # Use the current branch name

      - name: Setup
        uses: ./.github/actions/setup
        with:
          env: ${{ env.GITHUB_TOKEN }}

      - name: Setup git permissions
        run: |
          git config --global user.name "wetransferplatform"
          git config --global user.email "platform+github@wetransfer.com"
          git config --global user.signingkey "$WETRANSFERPLATFORM_GPG_KEYID"
          git config --global commit.gpgsign true
        shell: bash
        env:
          WETRANSFERPLATFORM_GPG_KEYID: ${{ secrets.WETRANSFERPLATFORM_GPG_KEYID }}

      - name: Import GPG key
        run: |
          echo "$WETRANSFERPLATFORM_GPG_KEY" | gpg --batch --import
        env:
          WETRANSFERPLATFORM_GPG_KEY: ${{ secrets.WETRANSFERPLATFORM_GPG_KEY }}
        shell: bash

      - name: Trust imported GPG key
        run: |
          KEY_ID=$(gpg --list-keys --with-colons | grep '^pub' | cut -d':' -f5)
          echo -e "trust\n5\ny\n" | gpg --command-fd 0 --batch --edit-key $KEY_ID
        shell: bash

      - name: Bump version
        id: version
        run: |
          # Bump version using yarn version
          yarn version --patch

          # Verify changes
          git status
          cat package.json

          # Extract the new version
          echo "NEW_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: Push changes and tags
        run: |
          git commit -am "Bump version to ${{ env.NEW_VERSION }}"
          git tag -a "v${{ env.NEW_VERSION }}" -m "Release version ${{ env.NEW_VERSION }}"
          git push -f origin ${{ github.ref_name }} --follow-tags
        shell: bash
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }} # Use the current branch name

      - name: Setup
        uses: ./.github/actions/setup
        with:
          env: ${{ env.GITHUB_TOKEN }}

      - name: Build package
        run: yarn build

      - name: Publish package
        run: yarn publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACCESS_TOKEN }}
