name: "Pull Request Workflow"

env:
  WT_GITHUB_TOKEN: ${{ secrets.WT_GITHUB_PACKAGES_RO }}
  GITHUB_TOKEN: ${{ secrets.WT_GITHUB_PACKAGES_RO }}
  NPM_PUBLISH_ACCESS_TOKEN: ${{ secrets.WT_GITHUB_REPO_RO_PACKAGES_RW }}

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: "20"

      - name: Run linting
        run: yarn lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: "20"

      - name: Run unit tests
        # run: yarn test
        run: |
          mkdir -p ./coverage &&
          touch ./coverage/summary.txt &&
          yarn test:coverage >> ./coverage/summary.txt
        shell: bash

      - name: Retrieve code coverage
        id: code_coverage
        run: |
          echo "Total coverage: $(grep -oE '[0-9]+\.[0-9]+%' -m 1 ./coverage/summary.txt | cut -d '.' -f1)% of statements" &&
          echo "coverage_percentage=$(grep -oE '[0-9]+\.[0-9]+%' -m 1 ./coverage/summary.txt | cut -d '.' -f1)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage

      - name: Bump version
        id: version
        run: |
          # Bump version using yarn version
          yarn version --patch

          # Extract the new version
          echo "NEW_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [linting, unit-test]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags

      - name: Build package
        run: yarn build

      - name: Publish package
        run: yarn publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: "$NPM_PUBLISH_ACCESS_TOKEN"

  # upload_coverage:
  #   name: Code Coverage
  #   uses: WeTransfer/gha-workflows/.github/workflows/upload_coverage.yml@main
  #   needs: unit-test
  #   with:
  #     coverage_percentage: ${{ needs.unit-test.outputs.coverage_percentage }}
  #     badge_green_limit: 90
  #     additional_artifacts: code-coverage
